---
ID: "0ad29087-6cc3-47ad-ad78-07d57c8afeeb"
Parent: "c3846043-8f65-4429-a852-77446986bdb2"
Template: "c3846043-8f65-4429-a852-77446986bdb2"
Path: "/sitecore/templates/Project/sai-local-setup/Rendering Parameters/TitleAndText Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260702T082911Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\prem_kumar1@epam.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\prem_kumar1@epam.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8295c263-cdd2-49ef-a91b-218e2e825ecb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\prem_kumar1@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260702T082911Z
